#pragma once

#include <iostream>
#include <vector>
#include <map>
#include <array>
#include <cmath>
#include <string>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <memory>
#include <limits>
#include <utility>
#include <stdexcept>
#include <functional>
#include <tuple>
#include <iomanip>
#include <Eigen/Dense>
#include "PPForm.hpp"
#include "BSpline.hpp"
#include "CurveFitting.hpp"
#include "NodeType.h"
#include "SplineType.h"
#include "BoundaryCondition.h"
#include "Intersection.hpp"